### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by astroman68** [vilari-mickopf/hyprprop#1]
How is this better/different than just running 'hyprctl clients'?

**Comment by vilari-mickopf** [comment]
`hyprctl clients` will print details for every window. If you are like me, and have 10 workspaces with at least 6-7 windows total at any given time, then you know how annoying it is to to go over all of them. `hyprprop` works more like `xprop`, it will allow you to select desired window (using `slurp`) and then it will list only properties of that selected window.
