### ISSUE TITLE
Error that follows execution. execvcp

### ISSUE THREAD

**Issue by sferg8** [vilari-mickopf/hyprprop#3]
Fresh install on hyprland-0.34.0-1

after running hyprland i get the following error

2024/01/25 15:54:16 socat[28025] E execvp("/home/someguy/.cache/yay/hyprevents-git/pkg/hyprevents-git/usr/share/hyprevents/event_loader", "/home/someguy/.cache/yay/hyprevents-git/pkg/hyprevents-git/usr/share/hyprevents/event_loader", "/home/someguy/.cache/yay/hyprprop-git/pkg/hyprprop-git/usr/share/hyprprop/event_handler"): No such file or directory

**Comment by sferg8** [comment]
Additionally I am not able to pick from other monitors, only the monitor that has the hyprprop terminal window

**Comment by vilari-mickopf** [comment]
This was PKGBUILD issue, but it's fixed and updated on aur.

I don't have additional monitors, so i have no ways of testing it, but feel free to open separate issue as a feature request. Patches are welcome.

**Comment by vilari-mickopf** [comment]
Multimonitor and special workspace support is now added.
