### ISSUE TITLE
Cannot capture windows in special workspaces Hyprland

### ISSUE THREAD

**Issue by ebiscaia** [vilari-mickopf/hyprprop#4]
Unfortunately it is not possible to capture the information of windows in special workspaces in Hyprland. The result will be of the window behind it.

**Comment by vilari-mickopf** [comment]
Yes, I am [capturing](https://github.com/vilari-mickopf/hyprprop/blob/46d12dbc002917917a79c59bcaefd5e2b3901898/hyprprop#L10) only the windows from the workspace as a workspace of the currently focused window. I will try to find a way to select all visible windows. That will fix multimonitor setups as well.

**Comment by vilari-mickopf** [comment]
I have added support for multiple monitors and special workspaces. The only issue is that currently there is [no event triggered when a special workspace is opened or closed](https://github.com/hyprwm/Hyprland/issues/7470), making it impossible to redraw only the currently visible windows automatically from hyprprop alone.

To force redrawing, you have two options:
1. Open or close a window after the special workspace is triggered, or switch between workspaces by moving back and forth to another workspace which will trigger hyprevents.
2. Manually send a signal when the togglespecialworkspace key is pressed by adding the following to your hyprland.conf file:
```
bind = $mod, <KEY>, togglespecialworkspace,
bind = $mod, <KEY>, exec, kill -USR1 "$(cat /tmp/hyprprop.pid)"
```
By binding both commands to the same key, Hyprland will execute them sequentially whenever the key is pressed.
