### ISSUE TITLE
LICENSE of the project unknown

### ISSUE THREAD

**Issue by doppelhelix** [vilari-mickopf/hyprprop#5]
Hi there
The licensing is a bit unclear. The git repository has no license but in the AUR `PKGBUILD` it's licensed as MIT. Could you add a license to git as well? (The same situation is in [hyprevents](https://github.com/vilari-mickopf/hyprevents))

**Comment by vilari-mickopf** [comment]
Thanks for pointing that out, I've probably just forgotten to put them on github as well. MIT is added now to both projects.
